### ISSUE TITLE
please help me i need some help

### ISSUE THREAD

**Issue by vks-leviathan** [whoeevee/EeveeSpotify#569] opened 2024-12-10 02:47 UTC
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

hi im very sorry this is the only way i found to ask some helps. I never somthing like like i wanted to try for the first time but i don't how it works, what do i have to install and to do ? im on a samsung laptop. thank you have a good night.

**Comment by yodaluca23** [comment] 2024-12-10 03:05
Duplicate of #564

**Closed** 2024-12-10 04:40 UTC
Labels: bug

**Comment by vks-leviathan** [comment] 2024-12-10 18:49
please i need someone to help me on live please i read the #564 but i don't really understood.

**Comment by asdfzxcvbn** [comment] 2024-12-10 20:33
> please i need someone to help me on live please i read the #564 but i don't really understood.

sorry but this isnt sideloading support, just issues for eeveespotify. refer all questions to sideloading forums like r/sideloaded
