### ISSUE TITLE
Lyrics limit randomly pops up

### ISSUE THREAD

**Issue by fugegate** [whoeevee/EeveeSpotify#120] opened 2024-05-21 15:44 UTC
https://github.com/whoeevee/EeveeSpotify/assets/46111388/b6cb843a-b6d8-4d5a-b16d-0d1c5860d2b4

**Comment by asdfzxcvbn** [comment] 2024-05-21 15:57
duplicate of #105

**Closed by asdfzxcvbn** 2024-05-21 15:57 UTC
