### ISSUE TITLE
Persistent offline.bnk Popup When Installed Through ESign Using A Free Certificate

### ISSUE THREAD

**Issue by Bryceshaw06** [whoeevee/EeveeSpotify#16] opened 2024-04-24 19:37 UTC
The provided ipa works without issue for me when installed using Altstore, but the same ipa won't work over ESign. It just throws the "offline.bnk file not found" error. Tested with both the swift and obj-c versions. 

(The reason that I need to use ESign is that it allows me to make more modifications to the signing certs and works with my no-revoke method. Altstore limits my installed number of apps and app extensions, and gets revoked)

**Comment by asdfzxcvbn** [comment] 2024-04-24 19:50
cant reproduce. maybe try uninstalling and reinstalling with a different bundle id.

**Comment by Bryceshaw06** [comment] 2024-04-24 19:51
Already tried :/

**Comment by asdfzxcvbn** [comment] 2024-04-24 19:54
and you tried both removing and keeping the embedded mobileprovision right? also are you sure you’re using a distribution cert?

**Comment by Bryceshaw06** [comment] 2024-04-24 19:57
Correct! I've tried removing the mobileprovision after signing and keeping the mobileprovision too. Tried that on both the swift and obj-c versions. My certificate I'm using is "iPhone Distribution: Bank of Chongqing Co., Ltd."

**Comment by asdfzxcvbn** [comment] 2024-04-24 20:00
okay, then im really not sure what the problem is. i havent heard any other reports regarding esign and im not sure if free certs have anything to do with it.

closing, unknown cause

**Comment by Bryceshaw06** [comment] 2024-04-24 20:02
Okay, thanks for the help. I think it would be useful to keep this issue open, just in case anyone else has a solution or the same problem. Obviously up to you though!

**Comment by asdfzxcvbn** [comment] 2024-04-25 01:09
> Just want to add here that it does not work on eSign through my paid certificate as well

are you having the same issue regarding the offline.bnk popup coming back over and over again, though?

**Comment by vuviett47** [comment] 2024-04-25 08:04
same with me though Sideloadly!

**Comment by vuviett47** [comment] 2024-04-25 08:04
Tweak doesn't work for me using Sideloadly!

**Comment by asdfzxcvbn** [comment] 2024-04-25 13:37
> > > Just want to add here that it does not work on eSign through my paid certificate as well
> 
> > 
> 
> > are you having the same issue regarding the offline.bnk popup coming back over and over again, though?
> 
> 
> 
> 
> 
> nope, it just doesn’t say anything at all. I log in then it says restart the app to get premium. I restart the app then nothing happens and premium isn’t activated

then it's not the same issue

**Comment by vuviett47** [comment] 2024-04-25 15:03
> > > > Just want to add here that it does not work on eSign through my paid certificate as well
> > 
> > > 
> > 
> > > are you having the same issue regarding the offline.bnk popup coming back over and over again, though?
> > 
> > 
> > 
> > 
> > 
> > nope, it just doesn’t say anything at all. I log in then it says restart the app to get premium. I restart the app then nothing happens and premium isn’t activated
> 
> then it's not the same issue

hmm if so I have same issue with him

**Comment by asdfzxcvbn** [comment] 2024-04-25 15:13
same install method? esign with free cert?

**Comment by vuviett47** [comment] 2024-04-25 15:16
no just install ipa with sideloadly. Restart app it still see me as free plan

**Comment by asdfzxcvbn** [comment] 2024-04-25 16:07
> no just install ipa with sideloadly. Restart app it still see me as free plan

but you do get the offline.bnk file popup right..?

**Comment by Bryceshaw06** [comment] 2024-04-25 16:25
The popup does not always show for me. Varys every install it seems

**Comment by asdfzxcvbn** [comment] 2024-04-29 13:39
this is not a tweak issue, probably nothing we can do, closing

**Closed** 2024-04-29 13:39 UTC

**Comment by Bryceshaw06** [comment] 2024-04-29 14:32
I would argue that this is a tweak issue to some extent, I don’t have any problem with the old Spotilife + eSign. It’s only eeveespotify

**Comment by asdfzxcvbn** [comment] 2024-04-29 16:34
> I would argue that this is a tweak issue to some extent, I don’t have any problem with the old Spotilife + eSign. It’s only eeveespotify

go ahead and read the source code then, we’re using simple methods that shouldn’t change depending on signing method, afaik spotilife changes everything at runtime

i might look into this later for the objc version
