### ISSUE TITLE
[Bug] Can't download music on app

### ISSUE THREAD

**Issue by Morettek** [whoeevee/EeveeSpotify#563] opened 2024-12-07 16:16 UTC
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

When I click to download the playlist locally, the download does not start. I'm in the last version, updated 2 days ago and instaled today.
![Imagem do WhatsApp de 2024-12-07 à(s) 13 14 37_0f56d5d6](https://github.com/user-attachments/assets/aa5bc5b0-b993-4b86-8850-75f1e4c27539)

**Comment by Blockr22** [comment] 2024-12-07 17:31
There is no way to download anything in this tweak. If u want offline music download & use YouTube music ultimate

**Comment by Morettek** [comment] 2024-12-07 17:54
Thanks for the tip, but I've already been able to download music with EveeSpotify in version EeveeSpotify-5.8-8.9.90.ipa

**Comment by yodaluca23** [comment] 2024-12-07 21:31
Official downloading is server sided, and cannot be spoofed. There is currently no downloading feature implemented, and there are no plans to.

**Comment by yodaluca23** [comment] 2024-12-07 21:45
> > Official downloading is server sided, and cannot be spoofed. There is currently no downloading feature implemented, and there are no plans to.
> 
> i know but theres an option to download the playlist locally, do you know how does it work?

That's only shown because the tweak patches the offline.bnk, so the app, locally, thinks you have premium, but no server side features will work, because the server knows you don't.

**Comment by asdfzxcvbn** [comment] 2024-12-07 23:21
there could be a bug on the serverside maybe? seems highly unlikely as idk how this would be possible

anyways, closing as even if you _were_ able to download in previous versions, it was never intended behavior from EeveeSpotify

**Closed by asdfzxcvbn** 2024-12-07 23:21 UTC
Labels: bug
