### ISSUE TITLE
it is incredible

### ISSUE THREAD

**Issue by Hellboy2018** [whoeevee/EeveeSpotify#154] opened 2024-05-31 09:04 UTC
I already tried the latest version and it is super good... there are some problems when sharing letters it only lets you choose one color... but thanks everything works excellent... Congratulations... you are great... let's see when we can use the maximum quality of listening
❤️👏🏽👏🏽👏🏽

**Comment by Hellboy2018** [comment] 2024-05-31 09:12
![image](https://github.com/whoeevee/EeveeSpotify/assets/171330187/c2bae2dc-7409-42f7-a2c0-00cc35c1dfd8)

**Comment by Hellboy2018** [comment] 2024-05-31 09:13
![image](https://github.com/whoeevee/EeveeSpotify/assets/171330187/26c288f6-cfbe-460a-af46-6a2294485643)

**Comment by asdfzxcvbn** [comment] 2024-05-31 11:35
this is a duplicate of #150 

> let's see when we can use the maximum quality of listening

never

**Closed by asdfzxcvbn** 2024-05-31 11:35 UTC
