### ISSUE TITLE
Auto play doesn't work [Bug] 

### ISSUE THREAD

**Issue by jfk2424** [whoeevee/EeveeSpotify#244] opened 2024-07-14 02:14 UTC
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Auto play doesn't seem to work, plays the same song over and over again. I tried to turn it off and on didn't seem to fix it.

**Comment by asdfzxcvbn** [comment] 2024-07-14 03:43
dupe of #230

**Closed by asdfzxcvbn** 2024-07-14 03:43 UTC
Labels: bug
