### ISSUE TITLE
Lyrics now have a cap

### ISSUE THREAD

**Issue by William-F11** [whoeevee/EeveeSpotify#43] opened 2024-04-30 20:38 UTC
The lyrics now have a monthly cap. When I try to click on, or even just watch the lyrics card it won’t let me unless I have Spotify Premium. 

![IMG_0929](https://github.com/whoeevee/EeveeSpotify/assets/133929371/166e1618-7938-42e2-ab3b-f91127ab4b7b)
![IMG_0930](https://github.com/whoeevee/EeveeSpotify/assets/133929371/7402fb5e-eb6d-49b3-9e00-198a548d9504)

**Comment by fugegate** [comment] 2024-04-30 20:40
SAME BRO 😭.   ![image](https://github.com/whoeevee/EeveeSpotify/assets/46111388/ba38b7d5-878d-4862-9478-c16bac4dd97e)

**Comment by asdfzxcvbn** [comment] 2024-04-30 21:11
duplicate of #42

**Closed by asdfzxcvbn** 2024-04-30 21:11 UTC
